movierater/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # OOB URL paths
    path('admin/', admin.site.urls),

    # Custom URL paths
    path('api/', include('movierater_api.urls')),
    path('', include('movierater_app.urls')),
]

movierater_app/urls.py
from django.urls import path

from . import views


app_name = "movierater_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

movierater_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from movierater_api.models import User


@login_required
def index(request):
    return render(request, "movierater_app/index.html")


#####
# Login/logout/register code 
#####
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("movierater_app:index"))
        else:
            return render(request, "movierater_app/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "movierater_app/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("movierater_app:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "movierater_app/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "movierater_app/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("movierater_app:index"))
    else:
        return render(request, "movierater_app/register.html")

movierater_app/templates/movierater_app/index.html
{% extends "movierater_app/layout.html" %}
{% load static %}

{% block body %}
<div id="app"></div>

<!-- Load React -->
<script src="https://unpkg.com/react@17/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>

<!-- Load App Scripts -->
<script src="{% static 'movierater_app/app.js' %}" type="module"></script>
{% endblock %}

movierater_app/templates/movierater_app/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="/">MovieRater</a>
            <ul class="navbar-nav justify-content-end">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movierater_app:logout' %}">Log Out ({{ user.username }})</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movierater_app:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movierater_app:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
            </div>
        </nav>
        <div class="container">
            <div class="alert d-none" role="alert" id="alertDiv"></div>
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

movierater_app/templates/movierater_app/login.html
{% extends "movierater_app/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'movierater_app:login' %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="my-3">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="my-3">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'movierater_app:register' %}">Register here.</a>

{% endblock %}

movierater_app/templates/movierater_app/register.html
{% extends "movierater_app/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'movierater_app:register' %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="my-3">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="my-3">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="my-3">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="my-3">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'movierater_app:login' %}">Log In here.</a>

{% endblock %}